# Copyright 2015 47Lining LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Applications folder where Nucleator jobs and scripts will be located
  file: path="{{ jenkins.lib }}/nucleator" state=directory owner=jenkins group=jenkins mode=0755
  sudo: yes

- name: Siteconfig folder
  file: path="{{ jenkins.lib }}/nucleator/siteconfig" state=directory owner=jenkins group=jenkins mode=0755
  sudo: yes

- name: Applications folder where webapps will be located
  file: path="{{ jenkins.lib }}/nucleator/applications" state=directory owner=jenkins group=jenkins mode=0755
  sudo: yes

- name: Applications folder where Nucleator jobs and scripts will be located
  file: path="{{ jenkins.lib }}/nucleator/scripts" state=directory owner=jenkins group=jenkins mode=0755
  sudo: yes

- name: Applications folder where Nucleator jobs and scripts will be located
  file: path="{{ jenkins.lib }}/nucleator/jobs" state=directory owner=jenkins group=jenkins mode=0755
  sudo: yes

- name: Nucleator jobs and scripts
  copy:
    dest="{{ jenkins.lib | osPathJoin('nucleator')}}"
    src=jobs
    mode=0644
    owner=jenkins
    group=jenkins
  sudo: yes

- name: Nucleator jobs and scripts
  copy:
    dest="{{ jenkins.lib | osPathJoin('nucleator', 'scripts')}}"
    src={{ 'internal_scripts' | osPathJoin('') }}
    mode=0644
    owner=jenkins
    group=jenkins
  sudo: yes