# Copyright 2015 47Lining LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Ansible Installation
- name: what is my ansible_os_family
  debug: msg="my family is {{ ansible_os_family }}"

- name: install packages used by or pre-requisite to ansible
  yum: name={{ item }} state=installed
  sudo: true
  when: ansible_os_family == 'RedHat'
  with_items:
    - git
    - cowsay
    - python26-pip
    - python27-pip
    - autoconf
    - gcc-c++
    - python27-devel
    - python26-devel

- name: install packages used by or pre-requisite to ansible
  apt: name={{ item }} state=present
  sudo: true
  when: ansible_os_family == 'Debian'
  with_items:
    - git
    - cowsay
    - python-pip
    - autoconf
    - g++
    - python2.7-dev

- name: install python prerequisites - paramiko
  pip: name=paramiko state=present

- name: install python prerequisites - PyYAML
  pip: name=PyYAML state=present

- name: install python prerequisites - Jinja2
  pip: name=Jinja2 state=present

- name: install python prerequisites - httplib2
  pip: name=httplib2 state=present

- name: install python prerequisites - boto
  pip: name=boto state=present

- name: "install Bethany's uber-cool sheep"
  copy: src=bethany-sheep.cow dest=/usr/share/cowsay/
  sudo: true

- name: determine whether ansible installed
  shell: "type ansible"
  ignore_errors: yes
  register: ansible_installed
  changed_when: false

- name: determine ansible version
  shell: ansible --version 2> /dev/null | head -1 | sed 's/^.* \([0-9\.]*\)$/\1/'
  when: ansible_installed.rc == 0
  register: ansible_version
  changed_when: false

- name: echo ansible version
  debug: msg="{{ ansible_version.stdout }}"
  when: ansible_installed.rc == 0
  changed_when: false

- include: install_ansible.yml
  when:  ansible_installed.rc > 0 or (ansible_version.stdout != ANSIBLE_TARGET_VERSION)
