# Copyright 2015 47Lining LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Do Not Tweak Config
  command: /bin/false
  register: config_needs_tweaked
  ignore_errors: True

#
# One of these will fail, however we don't really know ahead of time
# whether we are running with or without authentication.  When first created,
# it is running without in which case adding the username option causes the safe-restart
# command to report "invalid argument"
#
- name: Restart NucleatorUI
  shell: java -jar {{ jenkins.cli_dest }} -s '{{jenkins_url}}' -noCertificateCheck safe-restart --username {{ nucleator_userinterface.user }} --password {{ nucleator_userinterface.password }}
  ignore_errors: True

- name: Restart NucleatorUI
  shell: java -jar {{ jenkins.cli_dest }} -s '{{jenkins_url}}' -noCertificateCheck safe-restart
  ignore_errors: True
